name: build
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 01 Checkout Code
      uses: actions/checkout@v1
    - name: 02 Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: 03 Build with dotnet
      run: dotnet build
    - name: 04 Run Unit test
      run: dotnet test /p:CollectCoverage=true  /p:CoverletOutput='../../'  /p:CoverletOutputFormat=cobertura
    - name: 05 Combin All Test Report 
      uses: danielpalme/ReportGenerator-GitHub-Action@v4.5.0
      with:
        reports: test/*/coverage.cobertura.xml
        targetdir: .
        reporttypes: Cobertura
    - name: 06 Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true